type TRequestBody = {
  id: number
  title: string
  clientName: string
  clmHeaderNumber: string
  clmLineNumber: string
  typeContract: string
  company: string
  status: string
  renewStartDate: string
  renewEndDate: string
  contractRenewQtd: number
  frequency: string
  scope: string
  contractTotalValue: number
  dollarExchangeRate: string
  totalValueUSD: string
  gm: string
  renewIndexPercentage: string
  index: number
  paymentCondition: string
  inclusionClauses: string
  inclusionDescription: string
  legalIndemnificationObligations: string
  legalWarrantyObligations: string
  legalDamageCap: string
  legalDamageCave: string
  legalLiquidatedDamages: string
  justify: string
  requestId: string
  currentLevel: number
  author: string
  approvalLevel: string
  phone: string
  contact: string
  antiCorruption: string
  uf: string
  sap: string
  createdAt: string
  updatedAt: string
  requesterName: string
  requesterEmail: string
  currentApproverName: string
}
