import { approverLevelOptions, companyOptions, companyTypeOptions, contractTypeOptions, ufOptions } from './options'

export const SSCFormDataInputs = [
  [
    {
      id: 1,
      type: 'input',
      labelText: 'Requester',
      inputName: 'requesterName',
      inputType: 'text',
      required: true,
      readonly: true,
    },
    {
      id: 2,
      type: 'input',
      labelText: 'Client Name',
      inputName: 'clientName',
      inputType: 'text',
      required: true,
      readonly: false,
    },
    {
      id: 3,
      type: 'input',
      labelText: 'CLM Number (Header)',
      inputName: 'clmHeaderNumber',
      inputType: 'text',
      required: true,
      readonly: false,
    },
  ],
  [
    {
      id: 4,
      type: 'input',
      labelText: 'CLM Number (Line)',
      inputName: 'clmLineNumber',
      inputType: 'text',
      required: false,
      readonly: false,
    },
    {
      id: 5,
      type: 'select',
      labelText: 'Contract Type',
      inputName: 'typeContract',
      inputType: '',
      required: true,
      readonly: false,
      options: contractTypeOptions,
    },
    {
      id: 6,
      type: 'select',
      labelText: 'Company',
      inputName: 'company',
      inputType: '',
      required: true,
      readonly: false,
      options: companyOptions,
    },
  ],
  [
    {
      id: 7,
      type: 'input',
      labelText: 'Start Date/Renewal',
      inputName: 'renewStartDate',
      inputType: 'date',
      required: true,
      readonly: false,
    },
    {
      id: 8,
      type: 'input',
      labelText: 'End Date/Renewal',
      inputName: 'renewEndDate',
      inputType: 'date',
      required: true,
      readonly: false,
    },
    {
      id: 9,
      type: 'select',
      labelText: 'Company Type',
      inputName: 'companyType',
      inputType: '',
      required: true,
      readonly: false,
      options: companyTypeOptions,
    },
  ],
  [
    {
      id: 10,
      type: 'input',
      labelText: 'Scope',
      inputName: 'scope',
      inputType: 'text',
      required: true,
      readonly: false,
    },
    {
      id: 11,
      type: 'input',
      labelText: 'Payment Condition',
      inputName: 'paymentCondition',
      inputType: 'text',
      required: false,
      readonly: false,
    },
    {
      id: 12,
      type: 'input',
      labelText: 'Contract Total Value',
      inputName: 'contractTotalValue',
      inputType: 'text',
      required: true,
      readonly: false,
    },
  ],
  [
    {
      id: 13,
      type: 'input',
      labelText: 'Dollar Exchange Rate',
      inputName: 'dollarExchangeRate',
      inputType: 'number',
      required: true,
      readonly: false,
      step: '0.01',
    },
    {
      id: 14,
      type: 'input',
      labelText: 'Total Value USD',
      inputName: 'totalValueUSD',
      inputType: 'number',
      required: true,
      readonly: false,
    },
    {
      id: 15,
      type: 'input',
      labelText: 'GM',
      inputName: 'gm',
      inputType: 'number',
      required: false,
      readonly: false,
    },
  ],
  [
    {
      id: 16,
      type: 'input',
      labelText: 'Inclusion Clauses',
      inputName: 'inclusionClauses',
      inputType: 'text',
      required: false,
      readonly: false,
    },
    {
      id: 17,
      type: 'input',
      labelText: 'Inclusion Description',
      inputName: 'inclusionDescription',
      inputType: '',
      required: false,
      readonly: false,
    },
    {
      id: 18,
      type: 'input',
      labelText: 'legal Indemnification Obligations',
      inputName: 'legalIndemnificationObligations',
      inputType: 'text',
      required: false,
      readonly: false,
    },
  ],
  [
    {
      id: 19,
      type: 'input',
      labelText: 'Legal Warranty Obligations',
      inputName: 'legalWarrantyObligations',
      inputType: 'text',
      required: false,
      readonly: false,
    },
    {
      id: 20,
      type: 'input',
      labelText: 'legal Damage Cap',
      inputName: 'legalDamageCap',
      inputType: 'text',
      required: false,
      readonly: false,
    },
    {
      id: 21,
      type: 'input',
      labelText: 'Legal Damage Cave',
      inputName: 'legalDamageCave',
      inputType: 'text',
      required: false,
      readonly: false,
    },
  ],
  [
    {
      id: 22,
      type: 'input',
      labelText: 'Legal Liquidated Damage',
      inputName: 'legalLiquidatedDamages',
      inputType: 'text',
      required: false,
      readonly: false,
    },
    {
      id: 23,
      type: 'input',
      labelText: 'Justify',
      inputName: 'justify',
      inputType: 'text',
      required: false,
      readonly: false,
    },
    {
      id: 24,
      type: 'input',
      labelText: 'Phone',
      inputName: 'phone',
      inputType: 'text',
      required: false,
      readonly: false,
    },
  ],
  [
    {
      id: 25,
      type: 'input',
      labelText: 'AntiCorruption',
      inputName: 'antiCorruption',
      inputType: 'text',
      required: false,
      readonly: false,
    },
    {
      id: 26,
      type: 'select',
      labelText: 'UF',
      inputName: 'uf',
      inputType: '',
      required: false,
      readonly: false,
      options: ufOptions,
    },
    {
      id: 27,
      type: 'input',
      labelText: 'SAP',
      inputName: 'sap',
      inputType: 'text',
      required: false,
      readonly: false,
    },
  ],
  [
    {
      id: 28,
      type: 'input',
      labelText: 'Contact',
      inputName: 'contact',
      inputType: 'email',
      required: false,
      readonly: false,
    },
    {
      id: 29,
      type: 'select',
      labelText: 'Approval level',
      inputName: 'approvalLevel',
      inputType: '',
      required: false,
      readonly: false,
      options: approverLevelOptions,
    },
    {
      id: 30,
      type: 'input',
      labelText: 'Upload Files',
      inputType: 'file',
      inputName: 'files',
      required: false,
      readonly: false,
    },
  ],
]
